# Update solution configuration from active carriers
# Runs on a nightly schedule but scheduled before other regular pipelines might be starting

# No automated trigger
trigger: none

# Trigger the pipeline automatically every night (at midnight UTC)
schedules:
  - cron: '0 0 * * *'
    displayName: Start midnight solution configuration update
    branches:
      include:
        - main
    always: true # Trigger even if there were no changes

resources:
  repositories:
    # Add a reference to the pipelinetemplates repository where all the templates are located
    # No need to clone them, the templates can be referenced directly
    - repository: pipelinetemplates
      type: github
      name: DIGITALLNature/DigitallPipelines
      endpoint: DIGITALL Pipelines Service Connection # TODO: Replace with your endpoint connection name
      ref: refs/heads/feature/chaining # ! Replace for sample

      # By default the default branch is used. If this is not the same default between projects
      # (for most it is main, but for some it still is master) or a different one should be
      # used, the ref mus be set:
      # ref: refs/heads/preview
      # ref: refs/heads/master

# By default use an ubuntu image
pool:
  vmImage: ubuntu-latest

parameters:
  # After updating the solution configuration, trigger the export of the solutions with the new configuration
  # > This requires the export pipeline to have a pipeline trigger for this pipeline filtered on the tag 'Trigger_Export'
  - name: triggerExport
    displayName: Trigger export of solutions
    type: boolean
    default: true

# Use existing variable groups
variables:
  - group: Power Platform Environment Development # TODO: Replace with your variable group name

# Extend from pipeline template that generates the solution configuration
extends:
  template: azure-pipeline-templates/pp-solution-configuration/generate-from-carrier.yml@pipelinetemplates
  parameters:
    serviceConnection: Power Platform Service Connection Development # TODO: Replace with your service connection name
    customTags:
      - Environment_Development # TODO: Replace with your custom tags
      - ${{ if eq(parameters.triggerExport, true) }}:
        - Trigger_Export
    triggerExport: parameters.triggerExport
