# Download website content to current repository
# Runs on a nightly schedule

# No automated triggers
trigger: none

# Trigger the pipeline automatically every night (at midnight UTC)
# By default only run on dev branch
schedules:
  - cron: '0 0 * * *'
    displayName: Start export solution
    branches:
      include:
        - dev
    always: true # Trigger even if there were no changes

resources:
  repositories:
    # Add a reference to the pipelinetemplates repository where all the templates are located
    # No need to clone them, the templates can be referenced directly
    - repository: pipelinetemplates
      type: github
      name: DIGITALLNature/DigitallPipelines
      endpoint: DIGITALL Pipelines Service Connection

      # By default the default branch is used. If this is not the same default between projects
      # (for most it is main, but for some it still is master) or a different one should be
      # used, the ref mus be set:
      # ref: refs/heads/preview
      # ref: refs/heads/master

# By default use an ubuntu image
pool:
  vmImage: ubuntu-latest

# Use default variable groups (see /docs/variable-groups.md) namely the variables:
# - PowerPlatformUrl
# - PowerPlatformServiceConnectionName
# - PowerPlatformWebsiteId
# - PowerPlatformWebsiteFolderName
variables:
  - group: Power Platform Environment Development
  - group: Power Platform Deployment Connection
  - group: Power Platform Website MyWebsiteName

# Extend from pipeline template that downloads the website content
extends:
  template: azure-pipeline-templates/pp-website/sync.yml@pipelinetemplates
  parameters:
    webSiteId: $(PowerPlatformWebsiteId)
    serviceConnection: $(PowerPlatformServiceConnectionName)