# Upload website to target environment automatically on merge

# Automatically trigger on commit to main
trigger:
  branches:
    include:
      - main

resources:
  repositories:
    # Add a reference to the pipelinetemplates repository where all the templates are located
    # No need to clone them, the templates can be referenced directly
    - repository: pipelinetemplates
      type: github
      name: DIGITALLNature/DigitallPipelines
      endpoint: DIGITALL Pipelines Service Connection

      # By default the default branch is used. If this is not the same default between projects
      # (for most it is main, but for some it still is master) or a different one should be
      # used, the ref mus be set:
      # ref: refs/heads/preview
      # ref: refs/heads/master

# By default use an ubuntu image
pool:
  vmImage: ubuntu-latest

# Use default variable groups (see /docs/variable-groups.md) namely the variables:
# - PowerPlatformUrl
# - PowerPlatformServiceConnectionName
# - PowerPlatformWebsiteId
# - PowerPlatformWebsiteFolderName
variables:
  - group: Power Platform Deployment Connection
  - group: Power Platform Website MyWebsiteName
  - group: Power Platform Environment Production

parameters:
  # Option to disable backup before upload
  - name: backup
    displayName: Make a backup before uploading
    type: boolean
    default: true

# Extend from pipeline template that uploads the website content
extends:
  template: azure-pipeline-templates/pp-website/upload-job.yml@pipelinetemplates
  parameters:
    webSiteId: $(PowerPlatformWebsiteId)
    folderName: $(PowerPlatformWebsiteFolderName)
    serviceConnection: $(PowerPlatformServiceConnectionName)
    devOpsEnvironment: Power Platform Website MyWebsiteName Production
    deploymentProfile: prod
    backup: ${{ parameters.backup }}